apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: n8n-platform
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | quote }}
  N8N_ENCRYPTION_KEY: {{ .Values.n8n.encryptionKey | quote }}
